Milestone # 1: Completed NYT Project
simandebvu/nyt-clone pull request #2
Opened 2020-05-07 18:03 UTC by santiagorodriguezbermudez

## Milestone 1:

In this milestone we accomplished:
- Created HTML structure for cloning the New York Times article
- Styled the HTML structure accordingly
- Corrected linters and HTML markup

2020-05-08 13:49 UTC, santiago-rodrig commented
## Pull Request under review by @santiago-rodrig (TSE)

2020-05-08 13:54 UTC, santiago-dev96 requested changes
# Changes required :no_entry_sign:

1. You must use an `aside` tag for the "Editors' picks" part

![image](https://user-images.githubusercontent.com/43162770/81412113-5da83e00-9111-11ea-8089-a9a00f826d47.png)

After implementing the changes submit another CRR (Code Review Request). You can find me in slack as **srodrig**, have a nice day :wave:!

2020-05-08 13:54 UTC, santiago-rodrig commented on index.html
> +                <h3 class="content-header">Editors picks</h3>
You must use an aside

2020-05-08 15:09 UTC, simandebvu commented on index.html
> +                <h3 class="content-header">Editors picks</h3>
## Code Review #1 
> Added aside tag @ recommended by @santiago-rodrig

2020-05-08 15:11 UTC, simandebvu commented
> Added aside tag

2020-05-08 15:12 UTC, simandebvu commented
## Code Review #1 

> Added aside tag as suggested by @santiago-rodrig

2020-05-09 09:01 UTC, serdg0 approved these changes
**Congratulations** @simandebvu :fireworks: :100: :fireworks: 

Feel free to merge.

Keep the good work in your next project!

**Happy Coding!** :computer: :nerd_face: 

**_Sergio Diaz_**

2020-05-09 14:46 UTC, merged